name: Build

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: quortex-registry-public

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      # Deduce the appropriate tag for the image
      # Inspired by the docker action https://github.com/actions-hub/docker
      - name: Compute image tag
        run: |
          IMAGE_TAG=${TAG} && \
          if [[ -z "${IMAGE_TAG}" ]]; then \
            IMAGE_TAG=${GITHUB_REF#*/}; \
            IMAGE_TAG=${IMAGE_TAG#*/}; \
            IMAGE_TAG=$(echo $IMAGE_TAG | sed -e "s#^v##"); \
            if [[ "$IMAGE_TAG" == "master" || "$IMAGE_TAG" == "main" ]]; then \
              IMAGE_TAG=latest; \
            fi \
          fi && \
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      # Build docker image
      - name: Build docker images
        run: make docker-build
        env:
          IMAGE_REPOSITORY: eu.gcr.io/${{ env.GCP_PROJECT_ID }}/kapitan-docs

      # Setup gcloud CLI
      - name: Setup Gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      # Push docker image to docker hub
      - name: Push docker images
        run: |
          gcloud auth configure-docker -q
          make docker-push
        env:
          IMAGE_REPOSITORY: eu.gcr.io/${{ env.GCP_PROJECT_ID }}/kapitan-docs
